dist: trusty
sudo: false
language: cpp
script:
- scripts/get-cmake.sh
- PATH="$TRAVIS_BUILD_DIR/tools/cmake/bin:$PATH" CC=gcc-6 CXX=g++-6
  scripts/build.sh --server --release --tests --verbose
- server/build/release/src/run_tests
compiler:
- gcc
env:
- CFLAGS= CXXFLAGS=
- CFLAGS=-m32 CXXFLAGS=-m32
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-multilib
    - g++-multilib
    - gcc-6
    - gcc-6-multilib
    - g++-6
    - g++-6-multilib
