dist: trusty
sudo: false
language: cpp
script:
- scripts/build.sh --server --release --tests
- server/build/release/run_tests
compiler:
- gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - g++-6-multilib
      - cmake
