os: linux
dist: trusty
language: cpp

branches:
  only:
  - master

install:
- ci/travis/install.sh

script:
- export BUILD_TYPE=relwithdebinfo
- ci/travis/build.sh
- ci/travis/test.sh

deploy:
  provider: script
  script: scripts/upload.sh $BUILD_TYPE
  skip_cleanup: true
  on:
    branch: master
    condition: $CC = gcc

compiler:
- gcc
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - zlib1g-dev
