dist: trusty
sudo: false
language: cpp
script: scripts/travis-build.sh
compiler:
- gcc
- clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-multilib
    - g++-multilib
    - gcc-6
    - gcc-6-multilib
    - g++-6
    - g++-6-multilib
