image: Visual Studio 2017

branches:
  only:
  - master

install:
- ps: Install-Product node 8
- scripts\install\patch.cmd
- scripts\install\foobar2000.cmd v1.3
- scripts\install\foobar2000.cmd v1.4
- scripts\install\foobar2000.cmd v1.5
- set PATH=%cd%\tools\patch;%PATH%

build_script:
- set BUILD_TYPE=RelWithDebInfo
- ci\appveyor\build.cmd

test_script: ci\appveyor\test.cmd
deploy_script: ci\appveyor\upload.cmd
