name: build

on:
  push:
    branches: [ $default-branch, 'github-actions' ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build_linux:
    runs-on: ubuntu-18.04

    env:
      BUILD_TYPE: relwithdebinfo

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print versions
      run: scripts/print-versions.sh

    - name: Install tools
      run: ci/github/install.sh

    - name: Build
      run: ci/github/build.sh

    - name: Test
      run: ci/github/test.sh

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: beefweb_linux
        path: build/${{ env.BUILD_TYPE }}/*.tar.gz
